// SPDX-License-Identifier: AGPL-3.0-or-later

module.exports = {
	locales: [
		'ar',
		'bg',
		'cs',
		'da',
		'de',
		'el',
		'en-GB',
		'en-US',
		'es-ES',
		'es-419',
		'fi',
		'fr',
		'he',
		'hi',
		'hr',
		'hu',
		'id',
		'it',
		'ja',
		'ko',
		'lt',
		'nl',
		'no',
		'pl',
		'pt-BR',
		'ro',
		'ru',
		'sv-SE',
		'th',
		'tr',
		'uk',
		'vi',
		'zh-CN',
		'zh-TW',
	],
	sourceLocale: 'en-US',
	// MUNDRACUNN: strings novas do fork nao passam pelo Weblate do upstream; idiomas sem traducao
	// caem no ingles em vez de quebrar o build (o compile do fork roda sem --strict).
	fallbackLocales: {default: 'en-US'},
	catalogs: [
		{
			path: 'src/features/i18n/locales/{locale}/messages',
			include: ['src'],
			exclude: ['**/node_modules/**', '**/*.d.ts'],
		},
	],
	format: 'po',
	compileNamespace: 'es',
};
